[package]
name = "Wally"
version = "0.1.0"
edition = "2025"

[dependencies]
axum = {version = "0.8.4", features = ["macros"]}
tokio = { version = "1.46.1", features = ["full"] }
tower-http = { version = "0.6.6", features = ["cors"] }
serde_json = "1.0.140"